name = "toolhub-nextjs"
compatibility_date = "2024-09-06"

[build]
command = "npm run build"
cwd = "."
watch_dir = "src"

[[pages_build_output_dir]]
directory = "out"

[env.production.vars]
# 生产环境变量
NODE_ENV = "production"

# 允许的域名配置
[env.production]
# 禁用Bot Fight Mode对广告脚本的影响
compatibility_flags = ["nodejs_compat"]
